name: cupertino_lists_enhanced
description: Enhanced cupertino lists. Provides a list of options in the style of the iOS settings app. Choose an item (or items) from a list of options.
version: 0.1.3
repository: https://github.com/NickPGibson/cupertino_lists_enhanced
issue_tracker: https://github.com/NickPGibson/cupertino_lists_enhanced/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: